apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    project: {{ .Values.projectName }}
    app: {{ .Values.appName }}
  ports:
    - port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}